export default {
    ADD_EVENT_TO_MY_EVENTSLIST: "ADD_EVENT_TO_MY_EVENTSLIST",
    ADD_NEW_EVENT: "ADD_NEW_EVENT",
    ADD_COMMENT: "ADD_COMMENT",
    GET_EVENTS_BY_TYPE: "GET_EVENTS_BY_TYPE",
    GET_EVENT_DETAILS: "GET_EVENT_DETAILS",
    GET_MY_EVENTLIST: "GET_MY_EVENTLIST",
}